version: '3'
services:
  ui:
    build: ./ui
    ports:
      - 3000:3000

  api:
    build: ./api
    ports:
      - 3002:3001
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: